//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BASEntities : DbContext
    {
        public BASEntities()
            : base("name=BASEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accp_Farmer_Dtls> Accp_Farmer_Dtls { get; set; }
        public virtual DbSet<bankMaster> bankMasters { get; set; }
        public virtual DbSet<districtMaster> districtMasters { get; set; }
        public virtual DbSet<districtWiseBank> districtWiseBanks { get; set; }
        public virtual DbSet<errorMaster> errorMasters { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Request_Bank_Wise_PaymentList_Details> Request_Bank_Wise_PaymentList_Details { get; set; }
        public virtual DbSet<Request_Bank_Wise_PaymentList_Header> Request_Bank_Wise_PaymentList_Header { get; set; }
        public virtual DbSet<Request_PaymentList_Details> Request_PaymentList_Details { get; set; }
        public virtual DbSet<Request_PaymentList_Header> Request_PaymentList_Header { get; set; }
        public virtual DbSet<Response_Payment_Ack_List> Response_Payment_Ack_List { get; set; }
        public virtual DbSet<Response_Payment_Authorization_List> Response_Payment_Authorization_List { get; set; }
        public virtual DbSet<Response_Payment_Authorization_Message> Response_Payment_Authorization_Message { get; set; }
        public virtual DbSet<Response_Payment_AuthorizationList_Details> Response_Payment_AuthorizationList_Details { get; set; }
        public virtual DbSet<Response_Payment_AuthorizationList_Header> Response_Payment_AuthorizationList_Header { get; set; }
        public virtual DbSet<schemeMaster> schemeMasters { get; set; }
        public virtual DbSet<schemeOfficerRole> schemeOfficerRoles { get; set; }
        public virtual DbSet<ServiceConfig> ServiceConfigs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<systemMaster> systemMasters { get; set; }
        public virtual DbSet<systemWiseBank> systemWiseBanks { get; set; }
        public virtual DbSet<Topup> Topups { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<allError> allErrors { get; set; }
        public virtual DbSet<M_PDS_BANKBRANCH> M_PDS_BANKBRANCH { get; set; }
        public virtual DbSet<PDS_BLOCKMASTER> PDS_BLOCKMASTER { get; set; }
        public virtual DbSet<PDS_DISTRICTMASTER> PDS_DISTRICTMASTER { get; set; }
        public virtual DbSet<Re_Process_Payment_Authorization_Message> Re_Process_Payment_Authorization_Message { get; set; }
        public virtual DbSet<Re_Process_PaymentList_Details> Re_Process_PaymentList_Details { get; set; }
        public virtual DbSet<Response_Paymemt_Ack_Message> Response_Paymemt_Ack_Message { get; set; }
        public virtual DbSet<Request_Payment_Rejection> Request_Payment_Rejection { get; set; }
    }
}
