//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accp_Farmer_Dtls
    {
        public string VCHFARMERCODE { get; set; }
        public string VCHFARMERNAME { get; set; }
        public string VCHFATHERNAME { get; set; }
        public string VCHMOBILENO { get; set; }
        public string NICFARMERID { get; set; }
        public string VCHACCHOLDERNM { get; set; }
        public string VCHACCOUNTNO { get; set; }
        public Nullable<int> INTBANKID { get; set; }
        public string VCHDISTID { get; set; }
        public string VCHBLOCKID { get; set; }
        public string VCHIFSCCODE { get; set; }
        public string GENDER { get; set; }
        public string CATEGOGY { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class allError
    {
        public int Sl_No { get; set; }
        public string Unique_MsgID { get; set; }
        public string Error_Code { get; set; }
        public string Error_Msg { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bankMaster
    {
        public string Bank_Code { get; set; }
        public string Bank_Name { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class districtMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public districtMaster()
        {
            this.districtWiseBanks = new HashSet<districtWiseBank>();
        }
    
        public string Dist_Code { get; set; }
        public string Dist_Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<districtWiseBank> districtWiseBanks { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class districtWiseBank
    {
        public string Dist_Code { get; set; }
        public string Bank_Code { get; set; }
        public string System_ID { get; set; }
    
        public virtual districtMaster districtMaster { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class errorMaster
    {
        public string Error_Code { get; set; }
        public string Error_Msg { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Message { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_PDS_BANKBRANCH
    {
        public int intBranchId { get; set; }
        public string vchDistId { get; set; }
        public string vchDistrict { get; set; }
        public Nullable<int> intBankId { get; set; }
        public string vchBankName { get; set; }
        public string vchBranchName { get; set; }
        public string IFSC_CODE { get; set; }
        public string NEW_IFSC_CODE { get; set; }
        public Nullable<int> intCreatedBy { get; set; }
        public Nullable<System.DateTime> dtmCreatedOn { get; set; }
        public Nullable<int> intUpdatedBy { get; set; }
        public Nullable<System.DateTime> dtmUpdatedOn { get; set; }
        public Nullable<int> intDeletedFlag { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDS_BLOCKMASTER
    {
        public string int_BlockID { get; set; }
        public string int_DistrictID { get; set; }
        public string vch_BlockName { get; set; }
        public string vch_BlockNameOr { get; set; }
        public string vch_BlockCode { get; set; }
        public string vch_DistrictCode { get; set; }
        public string vchBlockType { get; set; }
        public Nullable<int> intBlockType { get; set; }
        public Nullable<int> intPPASS { get; set; }
        public Nullable<System.DateTime> dtmCreatedOn { get; set; }
        public string NIC_BlockCode { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDS_DISTRICTMASTER
    {
        public string int_DistrictID { get; set; }
        public string vch_DistrictName { get; set; }
        public string vch_DistrictNameOr { get; set; }
        public string vch_DistrictCode { get; set; }
        public Nullable<int> int_AdminId { get; set; }
        public Nullable<int> int_RDCType { get; set; }
        public string vch_RDC { get; set; }
        public Nullable<System.DateTime> dtmCreatedOn { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Re_Process_Payment_Authorization_Message
    {
        public string Unique_Message_Id { get; set; }
        public string Agency_ID { get; set; }
        public string Agency_Name { get; set; }
        public string Scheme_Code { get; set; }
        public string Instruction_Id { get; set; }
        public string Unique_Credit_Transaction_Id { get; set; }
        public Nullable<decimal> Payment_Amount_Center_Share { get; set; }
        public Nullable<decimal> Payment_Amount_State_Share { get; set; }
        public Nullable<decimal> Total_Payment_Amount { get; set; }
        public string Bank_Post_Office_Name { get; set; }
        public string Bank_Post_Office_Branch { get; set; }
        public string Scheme_Specific_Id { get; set; }
        public string PFMS_Beneficiary_Code { get; set; }
        public string Beneficiary_type { get; set; }
        public string Beneficiary_Title { get; set; }
        public string Beneficiary_Name { get; set; }
        public string Bank_Account_number { get; set; }
        public string Aadhaar_Number { get; set; }
        public string Record_Status { get; set; }
        public string Rejection_Reason_Code { get; set; }
        public string Rejection_Narration { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Re_Process_PaymentList_Details
    {
        public string Unique_Message_Id { get; set; }
        public string Payment_Instruction_Order_Number { get; set; }
        public string Unique_Credit_Transaction_Id { get; set; }
        public Nullable<decimal> Payment_Amount_Center_Share { get; set; }
        public Nullable<decimal> Payment_Amount_State_Share { get; set; }
        public Nullable<decimal> Total_Payment_Amount { get; set; }
        public string Bank_Post_Office_Name { get; set; }
        public string Bank_Post_Office_Branch { get; set; }
        public string Scheme_Specific_Id { get; set; }
        public string PFMS_Beneficiary_Code { get; set; }
        public string Beneficiary_type { get; set; }
        public string Beneficiary_Title { get; set; }
        public string Beneficiary_Name { get; set; }
        public string District_Code { get; set; }
        public string State_Code { get; set; }
        public string Bank_PostOffice_Account_number { get; set; }
        public string Aadhaar_Number { get; set; }
        public string Payment_Purpose_Component_Code { get; set; }
        public Nullable<decimal> Payment_Amount_Center_Share1 { get; set; }
        public Nullable<decimal> Payment_Amount_State_Share1 { get; set; }
        public Nullable<decimal> Total_Payment_Amount1 { get; set; }
        public string Sub_System_Id { get; set; }
        public string Sub_System_User { get; set; }
        public System.DateTime Payment_From_Date { get; set; }
        public System.DateTime Payment_To_Date { get; set; }
        public string Reference_Document_Information_Number { get; set; }
        public Nullable<System.DateTime> Reference_Document_Information_Date { get; set; }
        public string Remark_for_Beneficiary { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_Bank_Wise_PaymentList_Details
    {
        public string Unique_Message_Id { get; set; }
        public string Payment_Instruction_Order_Number { get; set; }
        public string Unique_Credit_Transaction_Id { get; set; }
        public Nullable<decimal> Payment_Amount_Center_Share { get; set; }
        public Nullable<decimal> Payment_Amount_State_Share { get; set; }
        public Nullable<decimal> Total_Payment_Amount { get; set; }
        public string Bank_PostOffice_Name { get; set; }
        public string Bank_PostOffice_Branch { get; set; }
        public string Scheme_Specific_Id { get; set; }
        public string PFMS_Benificiary_Code { get; set; }
        public string Benificiary_Title { get; set; }
        public string Benificiary_Name { get; set; }
        public string District_Code { get; set; }
        public string State_Code { get; set; }
        public string Bank_PostOffice_Account_Number { get; set; }
        public string Aadhar_Number { get; set; }
        public string Remark_For_Benificiary { get; set; }
    
        public virtual Request_Bank_Wise_PaymentList_Header Request_Bank_Wise_PaymentList_Header { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_Bank_Wise_PaymentList_Header
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request_Bank_Wise_PaymentList_Header()
        {
            this.Request_Bank_Wise_PaymentList_Details = new HashSet<Request_Bank_Wise_PaymentList_Details>();
        }
    
        public string Unique_Message_Id { get; set; }
        public Nullable<System.DateTime> Message_Date_Time { get; set; }
        public Nullable<int> Records_Count { get; set; }
        public Nullable<decimal> Control_Sum { get; set; }
        public string Data_Source { get; set; }
        public string Destination { get; set; }
        public string Institution_Id { get; set; }
        public string Institution_Name { get; set; }
        public string Scheme_Code { get; set; }
        public string Payment_Method { get; set; }
        public Nullable<System.DateTime> Required_Execution_Date { get; set; }
        public Nullable<int> SentStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request_Bank_Wise_PaymentList_Details> Request_Bank_Wise_PaymentList_Details { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_Payment_Rejection
    {
        public string Unique_Message_Id { get; set; }
        public string Reson_of_rejection { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_PaymentList_Details
    {
        public string Unique_Message_Id { get; set; }
        public string Payment_Instruction_Order_Number { get; set; }
        public string Unique_Credit_Transaction_Id { get; set; }
        public Nullable<decimal> Payment_Amount_Center_Share { get; set; }
        public Nullable<decimal> Payment_Amount_State_Share { get; set; }
        public Nullable<decimal> Total_Payment_Amount { get; set; }
        public string Bank_Post_Office_Name { get; set; }
        public string Bank_Post_Office_Branch { get; set; }
        public string Scheme_Specific_Id { get; set; }
        public string PFMS_Beneficiary_Code { get; set; }
        public string Beneficiary_type { get; set; }
        public string Beneficiary_Title { get; set; }
        public string Beneficiary_Name { get; set; }
        public string District_Code { get; set; }
        public string State_Code { get; set; }
        public string Bank_PostOffice_Account_number { get; set; }
        public string Aadhaar_Number { get; set; }
        public string Payment_Purpose_Component_Code { get; set; }
        public Nullable<decimal> Payment_Amount_Center_Share1 { get; set; }
        public Nullable<decimal> Payment_Amount_State_Share1 { get; set; }
        public Nullable<decimal> Total_Payment_Amount1 { get; set; }
        public string Sub_System_Id { get; set; }
        public string Sub_System_User { get; set; }
        public System.DateTime Payment_From_Date { get; set; }
        public System.DateTime Payment_To_Date { get; set; }
        public string Reference_Document_Information_Number { get; set; }
        public Nullable<System.DateTime> Reference_Document_Information_Date { get; set; }
        public string Remark_for_Beneficiary { get; set; }
        public string FMN_CAPACITY { get; set; }
        public string FMN_IMPLIMENT { get; set; }
        public string FMN_SUB_IMPLIMENT { get; set; }
    
        public virtual Request_PaymentList_Header Request_PaymentList_Header { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_PaymentList_Header
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request_PaymentList_Header()
        {
            this.Request_PaymentList_Details = new HashSet<Request_PaymentList_Details>();
        }
    
        public string Unique_Message_Id { get; set; }
        public System.DateTime Message_Date_Time { get; set; }
        public int Records_Count { get; set; }
        public decimal Control_Sum { get; set; }
        public string Data_Source { get; set; }
        public string Destination { get; set; }
        public string Initiating_Party_Name { get; set; }
        public string Initiating_Party_Code { get; set; }
        public string Batch_ID { get; set; }
        public System.DateTime Batch_Date { get; set; }
        public string Centre_Authority_Code { get; set; }
        public string State_Authority_Code { get; set; }
        public string Institution_Id { get; set; }
        public string Institution_Name { get; set; }
        public string Scheme_Code { get; set; }
        public string Payment_Method { get; set; }
        public Nullable<System.DateTime> Required_Execution_Date { get; set; }
        public string File_Status { get; set; }
        public Nullable<System.DateTime> AcceptedDate { get; set; }
        public string ipAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request_PaymentList_Details> Request_PaymentList_Details { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Response_Paymemt_Ack_Message
    {
        public string Unique_Message_Id { get; set; }
        public string Beneficiary_Scheme_Specific_Id { get; set; }
        public string PFMS_Beneficiary_Code { get; set; }
        public string Record_Level_Status { get; set; }
        public string Reject_Failure_Reason_Code { get; set; }
        public string Reject_Failure_Reason_Narration { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Response_Payment_Ack_List
    {
        public string Unique_Message_Id { get; set; }
        public System.DateTime Message_Date_Time { get; set; }
        public Nullable<int> Records_Count { get; set; }
        public string Data_Source { get; set; }
        public string Destination { get; set; }
        public string Original_Message_Id { get; set; }
        public string Original_Message_Name { get; set; }
        public Nullable<int> Number_of_Records_in_Original_File { get; set; }
        public Nullable<decimal> Control_Sum_of_Original_File { get; set; }
        public Nullable<System.DateTime> Created_date_time_of_Original_File { get; set; }
        public string Group_Status_File_Level_Status { get; set; }
        public string Batch_Id { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Response_Payment_Authorization_List
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Response_Payment_Authorization_List()
        {
            this.Response_Payment_Authorization_Message = new HashSet<Response_Payment_Authorization_Message>();
        }
    
        public string Unique_Message_Id { get; set; }
        public Nullable<System.DateTime> Message_Date_Time { get; set; }
        public int Records_Count { get; set; }
        public decimal Control_Sum { get; set; }
        public string Data_Source { get; set; }
        public string Destination { get; set; }
        public string Initiating_Party_Name { get; set; }
        public string Initiating_Party_Code { get; set; }
        public string Batch_ID { get; set; }
        public Nullable<System.DateTime> Batch_Date { get; set; }
        public string Centre_Authority_Code { get; set; }
        public string State_Authority_Code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Response_Payment_Authorization_Message> Response_Payment_Authorization_Message { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Response_Payment_Authorization_Message
    {
        public string Unique_Message_Id { get; set; }
        public string Agency_ID { get; set; }
        public string Agency_Name { get; set; }
        public string Scheme_Code { get; set; }
        public string Instruction_Id { get; set; }
        public string Unique_Credit_Transaction_Id { get; set; }
        public Nullable<decimal> Payment_Amount_Center_Share { get; set; }
        public Nullable<decimal> Payment_Amount_State_Share { get; set; }
        public Nullable<decimal> Total_Payment_Amount { get; set; }
        public string Bank_Post_Office_Name { get; set; }
        public string Bank_Post_Office_Branch { get; set; }
        public string Scheme_Specific_Id { get; set; }
        public string PFMS_Beneficiary_Code { get; set; }
        public string Beneficiary_type { get; set; }
        public string Beneficiary_Title { get; set; }
        public string Beneficiary_Name { get; set; }
        public string Bank_Account_number { get; set; }
        public string Aadhaar_Number { get; set; }
        public string Record_Status { get; set; }
        public string Rejection_Reason_Code { get; set; }
        public string Rejection_Narration { get; set; }
        public string Resent_Status { get; set; }
        public string AM_Status { get; set; }
    
        public virtual Response_Payment_Authorization_List Response_Payment_Authorization_List { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Response_Payment_AuthorizationList_Details
    {
        public string Unique_Message_Id { get; set; }
        public string Original_End_To_End { get; set; }
        public string Benificiary_Scheme_Specific_Id { get; set; }
        public string PFMS_Benificiary_Code { get; set; }
        public string Record_Level_Status { get; set; }
        public string Reject_Reason_Code { get; set; }
        public string Reject_Reason_Narration { get; set; }
    
        public virtual Response_Payment_AuthorizationList_Header Response_Payment_AuthorizationList_Header { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Response_Payment_AuthorizationList_Header
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Response_Payment_AuthorizationList_Header()
        {
            this.Response_Payment_AuthorizationList_Details = new HashSet<Response_Payment_AuthorizationList_Details>();
        }
    
        public string Unique_Message_Id { get; set; }
        public System.DateTime Message_Date_Time { get; set; }
        public int Records_Count { get; set; }
        public string Data_Source { get; set; }
        public string Destination { get; set; }
        public string Original_Message_Id { get; set; }
        public string Original_Message_Name { get; set; }
        public int Number_Of_Records_In_Original_File { get; set; }
        public decimal Control_Sum_Of_Original_File { get; set; }
        public Nullable<System.DateTime> Created_Date_Of_Original_File { get; set; }
        public string Group_Or_File_Level_Status { get; set; }
        public string Batch_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Response_Payment_AuthorizationList_Details> Response_Payment_AuthorizationList_Details { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class schemeMaster
    {
        public string Scheme_Code { get; set; }
        public string Scheme_Name { get; set; }
        public Nullable<decimal> Slab_Amount { get; set; }
        public string Account_Number { get; set; }
        public string Bank_Name { get; set; }
        public string IFSC_Code { get; set; }
        public Nullable<decimal> Max_Limit_Transfer { get; set; }
        public string System_ID { get; set; }
    
        public virtual systemMaster systemMaster { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class schemeOfficerRole
    {
        public string UserID { get; set; }
        public string Scheme_Code { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceConfig
    {
        public int id { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Status { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdiagram
    {
        public string name { get; set; }
        public int principal_id { get; set; }
        public int diagram_id { get; set; }
        public Nullable<int> version { get; set; }
        public byte[] definition { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class systemMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public systemMaster()
        {
            this.schemeMasters = new HashSet<schemeMaster>();
        }
    
        public string System_ID { get; set; }
        public string TID_Url { get; set; }
        public string RequestFolder_Path { get; set; }
        public string ResponseFolder_Path { get; set; }
        public string BankXml_Path { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Port { get; set; }
        public string PathType { get; set; }
        public Nullable<decimal> Ceiling_Amount { get; set; }
        public string bankResposePath { get; set; }
        public string BankUserName { get; set; }
        public string BankPassword { get; set; }
        public string BankPort { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<schemeMaster> schemeMasters { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class systemWiseBank
    {
        public string System_ID { get; set; }
        public string Bank_Code { get; set; }
        public string Account_Number { get; set; }
        public Nullable<decimal> Opening_Balance { get; set; }
        public string BankUrlPath { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string type { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topup
    {
        public int sl_no { get; set; }
        public string Bank_Name { get; set; }
        public string Account_Number { get; set; }
        public Nullable<decimal> Topup_amount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Topup Topup1 { get; set; }
        public virtual Topup Topup2 { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string imei { get; set; }
        public string passwordHash { get; set; }
        public string System_Id { get; set; }
        public string Employee_Code { get; set; }
        public string Employee_Name { get; set; }
    }
}
