//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class block
    {
        public string PFMS_Dist_Code { get; set; }
        public string PFMS_Block_Code { get; set; }
        public string block_name { get; set; }
        public string Nblock_code { get; set; }
        public string Nic_Block_Code { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_FARMER_REGISTRATION
    {
        public int INTFARMERID { get; set; }
        public string CHFARMERTYPE { get; set; }
        public string VCHFARMERCODE { get; set; }
        public string VCHEXISTFRCODE { get; set; }
        public string VCHPACSCODE { get; set; }
        public string VCHDISTID { get; set; }
        public string VCHBLOCKID { get; set; }
        public string VCHGPID { get; set; }
        public string VCHVILLAGEID { get; set; }
        public Nullable<int> INTTITLE { get; set; }
        public string VCHFARMERNAME { get; set; }
        public string VCHFATHERNAME { get; set; }
        public Nullable<int> INTRELATION { get; set; }
        public Nullable<int> INTGENDER { get; set; }
        public Nullable<int> INTCATEGOGY { get; set; }
        public Nullable<System.DateTime> DTMDOB { get; set; }
        public Nullable<int> INTAGE { get; set; }
        public string CHAGESTATUS { get; set; }
        public string VCHVOTERIDCARDNO { get; set; }
        public string VCHAADHARNO { get; set; }
        public string VCHMOBILENO { get; set; }
        public Nullable<int> INTFAMILYMEMBERS { get; set; }
        public string VCHACCHOLDERNM { get; set; }
        public string VCHACCOUNTNO { get; set; }
        public Nullable<int> INTBANKID { get; set; }
        public Nullable<int> INTBRANCHID { get; set; }
        public string VCHIFSCCODE { get; set; }
        public string CHACCSTATUS { get; set; }
        public Nullable<System.DateTime> DTMACCVERIFIEDON { get; set; }
        public string VCHPINCODE { get; set; }
        public Nullable<int> INTDELETEDFLAG { get; set; }
        public Nullable<int> INTCREATEDBY { get; set; }
        public Nullable<System.DateTime> DTMCREATEDON { get; set; }
        public Nullable<int> INTUPDATEDBY { get; set; }
        public Nullable<System.DateTime> DTMUPDATEDON { get; set; }
        public Nullable<int> INTPFMSVERIFIED { get; set; }
        public Nullable<int> INTREJECTED { get; set; }
        public string NICFARMERID { get; set; }
        public Nullable<bool> PFMSST { get; set; }
        public string CHAPFMSSTATUS { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NIC_farmer_updated_by_aao
    {
        public Nullable<int> INTFARMERID { get; set; }
        public string VCHACCOUNTNO { get; set; }
        public Nullable<int> INTBANKID { get; set; }
        public Nullable<int> INTBRANCHID { get; set; }
        public string VCHIFSCCODE { get; set; }
        public string VCHACCHOLDERNM { get; set; }
        public string VCHAADHARNO { get; set; }
        public string VCHMOBILENO { get; set; }
        public string VCHFARMERCODE { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_on { get; set; }
        public Nullable<int> status { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_Payment_tblHeader
    {
        public string CPAID { get; set; }
        public string AgencyName { get; set; }
        public string PaymentHead { get; set; }
        public string KMS { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Time { get; set; }
        public string PaymentMode { get; set; }
        public string Status { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_Payment_tblTransaction
    {
        public string CPAID { get; set; }
        public string TransactionID { get; set; }
        public string FarmerID { get; set; }
        public string FarmerName { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public string IFSC { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Scheme_Speciefic_ID { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_tbl_Beneficiary_List
    {
        public string Unique_Message_Id { get; set; }
        public string Message_Date_Time { get; set; }
        public int Record_Count { get; set; }
        public string Data_Source { get; set; }
        public string Destination { get; set; }
        public string Initiating_Party_Name { get; set; }
        public string Initiating_Party_Code { get; set; }
        public string Batch_ID { get; set; }
        public string Batch_Date { get; set; }
        public string Generate_Status { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_tbl_Beneficiary_Message
    {
        public string Unique_Message_Id { get; set; }
        public string Agency_ID { get; set; }
        public string Agency_Name { get; set; }
        public string Scheme_Code { get; set; }
        public string Purpose { get; set; }
        public string Scheme_Specific_ID { get; set; }
        public string PFMS_Beneficiary_Code { get; set; }
        public string Beneficiary_type { get; set; }
        public string Beneficiary_Title { get; set; }
        public string Beneficiary_Name { get; set; }
        public string BeneficiaryName_in_Regional { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Date_of_Birth { get; set; }
        public string F_M_H_Flag { get; set; }
        public string Father_Mother_name { get; set; }
        public string Father_Mother_name_regional { get; set; }
        public string Category { get; set; }
        public string Religion { get; set; }
        public string YearOfPass { get; set; }
        public string Address_Line_1 { get; set; }
        public string Address_Line_2 { get; set; }
        public string Address_Line_3 { get; set; }
        public Nullable<int> Pin_Code { get; set; }
        public string Village_Code { get; set; }
        public string Town_Code { get; set; }
        public string Block_Code { get; set; }
        public string Tehsil_Code { get; set; }
        public string District_Census_Code { get; set; }
        public string State_Census_Code { get; set; }
        public string Country { get; set; }
        public string Aadhaar_Number { get; set; }
        public string Bank_Name { get; set; }
        public string Branch_Id { get; set; }
        public string IFSC_Code { get; set; }
        public string Bank_Account_number { get; set; }
        public string Phone_Number { get; set; }
        public string Mobile_number { get; set; }
        public string Email { get; set; }
    
        public virtual Tbl_Dist Tbl_Dist { get; set; }
        public virtual Tbl_Bank Tbl_Bank { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_tbl_Payment_List
    {
        public string Unique_Message_Id { get; set; }
        public string Payment_Instruction_Order_Number { get; set; }
        public string Unique_Credit_Transaction_Id { get; set; }
        public Nullable<decimal> Payment_Amount_Center_Share { get; set; }
        public Nullable<decimal> Payment_Amount_State_Share { get; set; }
        public Nullable<decimal> Total_Payment_Amount { get; set; }
        public string Bank_Post_Office_Name { get; set; }
        public string Bank_Post_Office_Branch { get; set; }
        public string Scheme_Specific_Id { get; set; }
        public string PFMS_Beneficiary_Code { get; set; }
        public string Beneficiary_type { get; set; }
        public string Beneficiary_Title { get; set; }
        public string Beneficiary_Name { get; set; }
        public string District_Code { get; set; }
        public string State_Code { get; set; }
        public string BankPost_Office_Account_number { get; set; }
        public string Aadhaar_Number { get; set; }
        public string Payment_Purpose_Component_Code { get; set; }
        public Nullable<decimal> Payment_Amount_Center_Share1 { get; set; }
        public Nullable<decimal> Payment_Amount_State_Share1 { get; set; }
        public Nullable<decimal> Total_Payment_Amount1 { get; set; }
        public string Sub_System_Id { get; set; }
        public string Sub_System_User { get; set; }
        public Nullable<System.DateTime> Data_created_Date_Time { get; set; }
        public System.DateTime Payment_From_Date { get; set; }
        public System.DateTime Payment_To_Date { get; set; }
        public string Reference_Document_Information_Number { get; set; }
        public Nullable<System.DateTime> Reference_Document_Information_Date { get; set; }
        public string Remark_for_Beneficiary { get; set; }
    
        public virtual Request_tbl_Payment_Message Request_tbl_Payment_Message { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_tbl_Payment_Message
    {
        public Request_tbl_Payment_Message()
        {
            this.Request_tbl_Payment_List = new HashSet<Request_tbl_Payment_List>();
        }
    
        public string Unique_Message_Id { get; set; }
        public System.DateTime Message_Date_Time { get; set; }
        public int Records_Count { get; set; }
        public decimal Control_Sum { get; set; }
        public string Data_Source { get; set; }
        public string Destination { get; set; }
        public string Initiating_Party_Name { get; set; }
        public string Initiating_Party_Code { get; set; }
        public string Batch_ID { get; set; }
        public System.DateTime Batch_Date { get; set; }
        public string Centre_Authority_Code { get; set; }
        public string State_Authority_Code { get; set; }
        public string Institution_ID { get; set; }
        public string Institution_Name { get; set; }
        public string Scheme_Code { get; set; }
        public string Payment_Method { get; set; }
        public System.DateTime Required_Execution_Date { get; set; }
        public string Generate_Status { get; set; }
    
        public virtual ICollection<Request_tbl_Payment_List> Request_tbl_Payment_List { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Response_CCB1
    {
        public int ID { get; set; }
        public string Remark { get; set; }
        public Nullable<double> DCCBCODE { get; set; }
        public Nullable<double> BRANCHCODE { get; set; }
        public string BANKNAME { get; set; }
        public string BRANCHNAME { get; set; }
        public string NAMEINREGISTRATION { get; set; }
        public string ACCOUNTNUMBERSENT { get; set; }
        public string ACCOUNTNUMBERRECEIVED { get; set; }
        public string NAMEINCBS { get; set; }
        public string IFSC_Code { get; set; }
        public string Scheme_Specific_ID { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Response_Payment_tblHeader
    {
        public string CPAID { get; set; }
        public string AgencyName { get; set; }
        public string PaymentHead { get; set; }
        public string KMS { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string PaymentMode { get; set; }
        public string Status { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Response_Payment_tblTransaction
    {
        public string CPAID { get; set; }
        public string TransactionID { get; set; }
        public string PStatus { get; set; }
        public string Descs { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public string IFSC { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Response_tbl_Beneficiary_Ack_Message
    {
        public string Unique_Message_Id { get; set; }
        public string Agency_ID { get; set; }
        public string Agency_Name { get; set; }
        public string Scheme_Code { get; set; }
        public string Purpose { get; set; }
        public string Scheme_Specific_ID { get; set; }
        public string PFMS_Beneficiary_Code { get; set; }
        public string Beneficiary_type { get; set; }
        public string Beneficiary_Status { get; set; }
        public string Rejection_Reason_Code { get; set; }
        public string Rejection_Reason_Narration { get; set; }
        public string Bank_Post_Office_Name { get; set; }
        public string Bank_Post_Office_Branch { get; set; }
        public string Bank_Account_Number { get; set; }
        public string Beneficiary_Title { get; set; }
        public string Beneficiary_Name { get; set; }
    
        public virtual Response_tbl_Message_Ack_List Response_tbl_Message_Ack_List { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Response_tbl_Beneficiary_Ack_Message_D
    {
        public string Unique_Message_Id { get; set; }
        public string Agency_ID { get; set; }
        public string Agency_Name { get; set; }
        public string Scheme_Code { get; set; }
        public string Purpose { get; set; }
        public string Scheme_Specific_ID { get; set; }
        public string PFMS_Beneficiary_Code { get; set; }
        public string Beneficiary_type { get; set; }
        public string Beneficiary_Status { get; set; }
        public string Rejection_Reason_Code { get; set; }
        public string Rejection_Reason_Narration { get; set; }
        public string Bank_Post_Office_Name { get; set; }
        public string Bank_Post_Office_Branch { get; set; }
        public string Bank_Account_Number { get; set; }
        public string Beneficiary_Title { get; set; }
        public string Beneficiary_Name { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Response_tbl_Beneficiary_Ack_Message_D2
    {
        public string Unique_Message_Id { get; set; }
        public string Agency_ID { get; set; }
        public string Agency_Name { get; set; }
        public string Scheme_Code { get; set; }
        public string Purpose { get; set; }
        public string Scheme_Specific_ID { get; set; }
        public string PFMS_Beneficiary_Code { get; set; }
        public string Beneficiary_type { get; set; }
        public string Beneficiary_Status { get; set; }
        public string Rejection_Reason_Code { get; set; }
        public string Rejection_Reason_Narration { get; set; }
        public string Bank_Post_Office_Name { get; set; }
        public string Bank_Post_Office_Branch { get; set; }
        public string Bank_Account_Number { get; set; }
        public string Beneficiary_Title { get; set; }
        public string Beneficiary_Name { get; set; }
    
        public virtual Response_tbl_Message_Ack_List Response_tbl_Message_Ack_List { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Response_tbl_Message_Ack_List
    {
        public Response_tbl_Message_Ack_List()
        {
            this.Response_tbl_Beneficiary_Ack_Message = new HashSet<Response_tbl_Beneficiary_Ack_Message>();
            this.Response_tbl_Beneficiary_Ack_Message_D2 = new HashSet<Response_tbl_Beneficiary_Ack_Message_D2>();
        }
    
        public string Unique_Message_Id { get; set; }
        public System.DateTime Message_Date_Time { get; set; }
        public int Record_Count { get; set; }
        public string Data_Source { get; set; }
        public string Destination { get; set; }
        public string Initiating_Party_Name { get; set; }
        public string Initiating_Party_Code { get; set; }
        public string Batch_ID { get; set; }
        public Nullable<System.DateTime> Batch_Date { get; set; }
    
        public virtual ICollection<Response_tbl_Beneficiary_Ack_Message> Response_tbl_Beneficiary_Ack_Message { get; set; }
        public virtual ICollection<Response_tbl_Beneficiary_Ack_Message_D2> Response_tbl_Beneficiary_Ack_Message_D2 { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Response_tbl_Paymemt_Ack_Message
    {
        public string Unique_Message_Id { get; set; }
        public string Original_End_to_End_Id { get; set; }
        public string Beneficiary_Scheme_Specific_Id { get; set; }
        public string PFMS_Beneficiary_Code { get; set; }
        public string Record_Level_Status { get; set; }
        public string Reject_Failure_Reason_Code { get; set; }
        public string Reject_Failure_Reason_Narration { get; set; }
    
        public virtual Response_tbl_Paymemt_Ack_Message Response_tbl_Paymemt_Ack_Message1 { get; set; }
        public virtual Response_tbl_Paymemt_Ack_Message Response_tbl_Paymemt_Ack_Message2 { get; set; }
        public virtual Response_tbl_Paymemt_Ack_Message Response_tbl_Paymemt_Ack_Message11 { get; set; }
        public virtual Response_tbl_Paymemt_Ack_Message Response_tbl_Paymemt_Ack_Message3 { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Response_tbl_Paymemt_Ack_Message_D
    {
        public string Unique_Message_Id { get; set; }
        public string Original_End_to_End_Id { get; set; }
        public string Beneficiary_Scheme_Specific_Id { get; set; }
        public string PFMS_Beneficiary_Code { get; set; }
        public string Record_Level_Status { get; set; }
        public string Reject_Failure_Reason_Code { get; set; }
        public string Reject_Failure_Reason_Narration { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Response_tbl_Payment_Ack_List
    {
        public string Unique_Message_Id { get; set; }
        public System.DateTime Message_Date_Time { get; set; }
        public int Records_Count { get; set; }
        public string Data_Source { get; set; }
        public string Destination { get; set; }
        public string Original_Message_Id { get; set; }
        public string Original_Message_Name { get; set; }
        public int Number_of_Records_in_Original_File { get; set; }
        public decimal Control_Sum_of_Original_File { get; set; }
        public System.DateTime Created_date_time_of_Original_File { get; set; }
        public string Group_Status_File_Level_Status { get; set; }
        public string Batch_Id { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Response_tbl_Payment_Authorization_List
    {
        public Response_tbl_Payment_Authorization_List()
        {
            this.Response_tbl_Payment_Authorization_Message = new HashSet<Response_tbl_Payment_Authorization_Message>();
        }
    
        public string Unique_Message_Id { get; set; }
        public System.DateTime Message_Date_Time { get; set; }
        public int Records_Count { get; set; }
        public decimal Control_Sum { get; set; }
        public string Data_Source { get; set; }
        public string Destination { get; set; }
        public string Initiating_Party_Name { get; set; }
        public string Initiating_Party_Code { get; set; }
        public string Batch_ID { get; set; }
        public System.DateTime Batch_Date { get; set; }
        public string Centre_Authority_Code { get; set; }
        public string State_Authority_Code { get; set; }
    
        public virtual ICollection<Response_tbl_Payment_Authorization_Message> Response_tbl_Payment_Authorization_Message { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Response_tbl_Payment_Authorization_Message
    {
        public string Unique_Message_Id { get; set; }
        public string Agency_ID { get; set; }
        public string Agency_Name { get; set; }
        public string Scheme_Code { get; set; }
        public string Instruction_Id { get; set; }
        public string Unique_Credit_Transaction_Id { get; set; }
        public Nullable<decimal> Payment_Amount_Center_Share { get; set; }
        public Nullable<decimal> Payment_Amount_State_Share { get; set; }
        public Nullable<decimal> Total_Payment_Amount { get; set; }
        public string Bank_Post_Office_Name { get; set; }
        public string Bank_Post_Office_Branch { get; set; }
        public string Scheme_Specific_Id { get; set; }
        public string PFMS_Beneficiary_Code { get; set; }
        public string Beneficiary_type { get; set; }
        public string Beneficiary_Title { get; set; }
        public string Beneficiary_Name { get; set; }
        public string Bank_Account_number { get; set; }
        public string Aadhaar_Number { get; set; }
        public string Record_Status { get; set; }
        public string Rejection_Reason_Code { get; set; }
        public string Rejection_Narration { get; set; }
    
        public virtual Response_tbl_Payment_Authorization_List Response_tbl_Payment_Authorization_List { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Bank
    {
        public Tbl_Bank()
        {
            this.Request_tbl_Beneficiary_Message = new HashSet<Request_tbl_Beneficiary_Message>();
        }
    
        public string Dist_Code { get; set; }
        public string Bank_Code { get; set; }
        public string Bank_Name { get; set; }
        public Nullable<int> PFMSStatus { get; set; }
        public Nullable<int> IntegrationStatus { get; set; }
    
        public virtual ICollection<Request_tbl_Beneficiary_Message> Request_tbl_Beneficiary_Message { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Branch
    {
        public string Branch_Code { get; set; }
        public string Bank_Code { get; set; }
        public string Branch_Name { get; set; }
        public string IFSC { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Dist
    {
        public Tbl_Dist()
        {
            this.Request_tbl_Beneficiary_Message = new HashSet<Request_tbl_Beneficiary_Message>();
        }
    
        public string Dist_Name { get; set; }
        public string PFMS_Dist_Code { get; set; }
        public string NDist_Code { get; set; }
        public string NICDIST_CODE { get; set; }
        public string NICDIST_NAME { get; set; }
        public string SHORT_NAME { get; set; }
    
        public virtual ICollection<Request_tbl_Beneficiary_Message> Request_tbl_Beneficiary_Message { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_FarmerApprove
    {
        public int Srl_No { get; set; }
        public string Farmer_Code { get; set; }
        public string PFMS_Code { get; set; }
        public string Farmer_ID { get; set; }
        public string Status { get; set; }
        public string SMS_ST { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_GP
    {
        public string GP_Code { get; set; }
        public string Block_Code { get; set; }
        public string GP_Name { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_BenificiaryAccpResponse
    {
        public string VCHACCOUNTNO { get; set; }
        public string VCHFARMERNAME { get; set; }
        public string VCHFATHERNAME { get; set; }
        public string VCHACCHOLDERNM { get; set; }
        public string VCHIFSCCODE { get; set; }
        public string NICFARMERID { get; set; }
        public string VCHFARMERCODE { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Village
    {
        public string villg_code { get; set; }
        public string gp_code { get; set; }
        public string villg_name { get; set; }
    }
}
namespace Model
{
    using System;
    
    public partial class REPORT_STATUSDETAILS_Result
    {
        public string FARMER_ID { get; set; }
        public string nTRANS { get; set; }
        public string reqMsgID { get; set; }
        public string respMsgID { get; set; }
        public Nullable<System.DateTime> DATES { get; set; }
        public string request { get; set; }
        public string BankPaid { get; set; }
        public string RESPONSEBULK { get; set; }
    }
}
