//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class JALANIDHI_DAO_AAO
    {
        public int ID { get; set; }
        public string DDA_CODE { get; set; }
        public string DDA_NAME { get; set; }
        public string DAO_CODE { get; set; }
        public string DAO_NAME { get; set; }
        public string BLK_CODE { get; set; }
        public string BLK_NAME { get; set; }
        public string AAO_CODE { get; set; }
        public string AAO_NAME { get; set; }
        public string CRDNTIAL { get; set; }
        public string PP { get; set; }
        public string VP { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK_FARMER
    {
        public string FARMER_ID { get; set; }
        public string TRANSACTION_ID { get; set; }
        public string CROPCATG_ID { get; set; }
        public string CROP_ID { get; set; }
        public string CROP_VERID { get; set; }
        public string CROP_CLASS { get; set; }
        public string Receive_Unitcd { get; set; }
        public string LOT_NUMBER { get; set; }
        public Nullable<int> BAG_SIZE_KG { get; set; }
        public Nullable<int> NO_OF_BAGS { get; set; }
        public Nullable<decimal> TOT_QTL { get; set; }
        public Nullable<decimal> ADMISSIBLE_SUBSIDY { get; set; }
        public Nullable<decimal> PRICE_QTL { get; set; }
        public Nullable<decimal> ALL_IN_COST_AMOUNT { get; set; }
        public string SCHEME_CODE_GOI { get; set; }
        public Nullable<decimal> TOT_SUB_AMOUNT_GOI { get; set; }
        public string SCHEME_CODE_SP { get; set; }
        public Nullable<decimal> TOT_SUB_AMOUNT_SP { get; set; }
        public Nullable<decimal> SUBSIDY_AMOUNT { get; set; }
        public string SEASON { get; set; }
        public string FIN_YEAR { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_ON { get; set; }
        public string USER_TYPE { get; set; }
        public string USERIP { get; set; }
        public string TRN_TYPE { get; set; }
        public string XML_Status { get; set; }
    }
}
