//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class stocknewEntities1 : DbContext
    {
        public stocknewEntities1()
            : base("name=stocknewEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<STOCK_FARMER> STOCK_FARMER { get; set; }
        public virtual DbSet<JALANIDHI_DAO_AAO> JALANIDHI_DAO_AAO { get; set; }
    }
}
