<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPages/SeedAdmin.master" AutoEventWireup="true" CodeFile="StatusOfSeedSubsidyPaymentFiles.aspx.cs" Inherits="Reports_StatusOfSeedSubsidyPaymentFiles" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder2" runat="Server">
    <div class="titleHeader">
        &nbsp; Schemewise Details
    </div>
    <br />
    <script>
        function getPrint(print_area) {
            var divToPrint = document.getElementById(print_area);
            var printWin = window.open('', 'Mail In', 'left=0,top=0,width=1000,height=600,status=0');
            printWin.document.write("<div align='center' style='width:1000px;margin:auto;padding-top:10px'>");
            printWin.document.write(divToPrint.outerHTML);
            printWin.document.write("</div>");
            printWin.document.close();
            printWin.focus();
            printWin.print();
        }
    </script>
    <ajax:UpdatePanel ID="updatepanel" runat="server" UpdateMode="Always">
        <ContentTemplate>
            <asp:Panel ID="Panel1" runat="server" Style="padding-top: 30px;" CssClass="tbltxt">
                <div style="width: 1220px; padding: 2px; margin: 0 auto;">
                    <div style="padding: 10px; width: 1200px;">
                        <table style="width: 100%; padding: 5px;" class="tabletxt" cellpadding="0" cellspacing="0">
                            <tr>
                                <td class="auto-style14" style="width: 74px">Session Year</td>
                                <td class="auto-style19">:</td>
                                <td class="auto-style15" style="width: 150px">
                                    <asp:DropDownList ID="drpSession" runat="server" CssClass="DropdownCss" AutoPostBack="True" OnSelectedIndexChanged="drpSession_SelectedIndexChanged">
                                    </asp:DropDownList></td>
                                <td class="auto-style7" style="width: 45px">Season </td>
                                <td>:</td>
                                <td class="auto-style17" style="width: 150px">
                                    <asp:DropDownList ID="drpSeassion" runat="server" CssClass="DropdownCss" AutoPostBack="True" OnSelectedIndexChanged="drpSeassion_SelectedIndexChanged">
                                    </asp:DropDownList></td>
                                <td style="width: 50px;" class="normaltd">Scheme</td>
                                <td style="width: 5px;">:</td>
                                <td style="width: 150px;">
                                    <asp:DropDownList ID="drpScheme" runat="server" CssClass="DropdownCss">
                                    </asp:DropDownList></td>
                                <td style="width: 50px;" class="normaltd">Dealer/PACS</td>
                                <td style="width: 5px;">:</td>
                                <td style="width: 150px;">
                                    <asp:DropDownList ID="ddlAppType" runat="server" CssClass="DropdownCss">
                                        <asp:ListItem Value="ALL">--ALL--</asp:ListItem>
                                        <asp:ListItem Value="Dealer">Dealer</asp:ListItem>
                                        <asp:ListItem Value="PACS">PACS</asp:ListItem>
                                    </asp:DropDownList></td>
                                <td style="width: 50px;" class="normaltd">Type</td>
                                <td style="width: 5px;">:</td>
                                <td style="width: 150px;">
                                    <asp:DropDownList ID="drpType" runat="server" CssClass="DropdownCss">
                                        <asp:ListItem Value="ALL">--All--</asp:ListItem>
                                        <asp:ListItem Value="RELNIC">Generated By NIC</asp:ListItem>
                                        <asp:ListItem Value="PENNIC">Not Generated By NIC</asp:ListItem>
                                    </asp:DropDownList></td>

                            </tr>
                        </table>
                        <table>
                            <tr>
                                <td>
                                    <asp:Button ID="btnSearch" runat="server" Text="Search" Width="98px" OnClientClick="return Valid();" OnClick="btnSearch_Click" />
                                    <asp:Button ID="btnExport" runat="server" Text="Export to Excel" Width="128px" OnClick="btnExport_Click" />
                                </td>
                            </tr>
                        </table>
                        <div id="divPrint">
        <table style="width: 100%;">
            <tr>
                <td>
                    <asp:GridView ID="gvDetails" runat="server"  AutoGenerateColumns="false">
                        <Columns>
                            <asp:BoundField DataField="Sl. No." HeaderText="Sl. No." />
                            <asp:BoundField DataField="Generated File Name" HeaderText="Generated File Name" />
                            <asp:BoundField DataField="File Date" HeaderText="File Date" />
                            <asp:BoundField DataField="No. of Transaction" HeaderText="No. of Transaction" />
                            <asp:BoundField DataField="No. of beneficiary" HeaderText="No. of beneficiary" />
                            <asp:BoundField DataField="Amount" HeaderText="Amount" />
                            <asp:BoundField DataField="Status" HeaderText="Status" />
                        </Columns>
                    </asp:GridView>
                    <asp:GridView ID="GridView1" runat="server" Visible="false"></asp:GridView>
                </td>
            </tr>
        </table>
        <table style="width: 100%;">
            <tr>
                <td>
                    <asp:Label ID="Pay_Rel" runat="server" />
                </td>
                <td>
                    <asp:Label ID="Pay_Pen" runat="server" />
                </td>
                <td>
                    <asp:Label ID="lblTotal" runat="server" />
                </td>
            </tr>
        </table>

        <fieldset class="tbl">
            <legend style="margin-left: 10px; font-weight: bold;"></legend>
            <%--<asp:Literal ID="litReport" runat="server"></asp:Literal>--%>
        </fieldset>
    </div>
                        
                    </div>

                </div>
                </fieldset>
                </div>
                </fieldset>
            </div>
            </div>
            <div style="height: 30px;">&nbsp;</div>
            </asp:Panel>

            <%--<asp:UpdateProgress runat="server" ID="Uprogress" AssociatedUpdatePanelID="updatepanel"
                          DisplayAfter="0">
                          <ProgressTemplate>
                              <div style="text-align: center; vertical-align: middle; position: absolute; top: 0px; left: 0px; z-index: 99; width: 100%; height: 1000px; background-color: #ededed; -ms-filter: 'progid:DXImageTransform.Microsoft.Alpha(Opacity=60)'; filter: progid:DXImageTransform.Microsoft.Alpha(opacity=60); -moz-opacity: 0.8; opacity: 0.8;"
                                  visible="true">
                                  <div style="width: 48px; height: 48px; margin: 0 auto; margin-top: 275px;">
                                      <asp:Image ImageUrl="~/images/loading.gif" Width="48px" Height="48px" runat="server"
                                          ID="TaskLoadingImage" />
                                  </div>
                                  <div style="font-family: Trebuchet MS; font-size: 12px; color: Red; text-align: center;">
                                      Please Wait ...
                                  </div>
                              </div>
                          </ProgressTemplate>
                      </asp:UpdateProgress>--%>
        </ContentTemplate>
        <Triggers>
            <%--<asp:AsyncPostBackTrigger ControlID="btnSearch" EventName="Click" />--%>

            <asp:PostBackTrigger ControlID="btnExport"></asp:PostBackTrigger>
            <asp:PostBackTrigger ControlID="btnExport"></asp:PostBackTrigger>
        </Triggers>
    </ajax:UpdatePanel>
    
</asp:Content>

