//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Complain_Table
{
    public int Complain_No { get; set; }
    public string Sco_code { get; set; }
    public string Asco_Code { get; set; }
    public string Complain_type { get; set; }
    public string Problem { get; set; }
    public byte[] Problem_file { get; set; }
    public string Complain_status { get; set; }
    public Nullable<System.DateTime> Complain_date { get; set; }
    public string Complain_Aproove { get; set; }
    public string File_Name { get; set; }
    public string File_Type { get; set; }
    public Nullable<System.DateTime> Approve_DateTime { get; set; }
    public string Remark { get; set; }

    public virtual Complain_Type_Table Complain_Type_Table { get; set; }
}

public partial class Complain_Type_Table
{
    public Complain_Type_Table()
    {
        this.Complain_Table = new HashSet<Complain_Table>();
    }

    public string Complain_type_Id { get; set; }
    public string Complain_Type { get; set; }

    public virtual ICollection<Complain_Table> Complain_Table { get; set; }
}
