//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class LoginAccess
{
    public long AccessID { get; set; }
    public string UserID { get; set; }
    public System.DateTime ActivityDate { get; set; }
    public string UserIP { get; set; }
    public string Login_Status { get; set; }
    public string OS { get; set; }
    public string BWSER { get; set; }

    public virtual Stock_Users Stock_Users { get; set; }
}

public partial class Stock_Agencies_Master
{
    public string AgenciesID { get; set; }
    public string AgenciesName { get; set; }
    public string IsActive { get; set; }
}

public partial class Stock_Crop_Master
{
    public Stock_Crop_Master()
    {
        this.Stock_CropVariety_Master = new HashSet<Stock_CropVariety_Master>();
        this.Stock_DateWiseStockDetails = new HashSet<Stock_DateWiseStockDetails>();
        this.STOCK_DEALERSALEDTL = new HashSet<STOCK_DEALERSALEDTL>();
        this.STOCK_DEALERSTOCK = new HashSet<STOCK_DEALERSTOCK>();
        this.STOCK_FARMER = new HashSet<STOCK_FARMER>();
        this.Stock_OpeningBalance = new HashSet<Stock_OpeningBalance>();
        this.Stock_ReceiveDetails = new HashSet<Stock_ReceiveDetails>();
        this.Stock_SaleDetails = new HashSet<Stock_SaleDetails>();
        this.Stock_StockDetails = new HashSet<Stock_StockDetails>();
    }

    public string Crop_ID { get; set; }
    public string CropCatg_ID { get; set; }
    public string Crop_Name { get; set; }
    public string IsActive { get; set; }

    public virtual Stock_CropCategory_Master Stock_CropCategory_Master { get; set; }
    public virtual ICollection<Stock_CropVariety_Master> Stock_CropVariety_Master { get; set; }
    public virtual ICollection<Stock_DateWiseStockDetails> Stock_DateWiseStockDetails { get; set; }
    public virtual ICollection<STOCK_DEALERSALEDTL> STOCK_DEALERSALEDTL { get; set; }
    public virtual ICollection<STOCK_DEALERSTOCK> STOCK_DEALERSTOCK { get; set; }
    public virtual ICollection<STOCK_FARMER> STOCK_FARMER { get; set; }
    public virtual ICollection<Stock_OpeningBalance> Stock_OpeningBalance { get; set; }
    public virtual ICollection<Stock_ReceiveDetails> Stock_ReceiveDetails { get; set; }
    public virtual ICollection<Stock_SaleDetails> Stock_SaleDetails { get; set; }
    public virtual ICollection<Stock_StockDetails> Stock_StockDetails { get; set; }
}

public partial class Stock_CropCategory_Master
{
    public Stock_CropCategory_Master()
    {
        this.Stock_Crop_Master = new HashSet<Stock_Crop_Master>();
        this.Stock_CropVariety_Master = new HashSet<Stock_CropVariety_Master>();
        this.Stock_DateWiseStockDetails = new HashSet<Stock_DateWiseStockDetails>();
        this.STOCK_DEALERSALEDTL = new HashSet<STOCK_DEALERSALEDTL>();
        this.STOCK_DEALERSTOCK = new HashSet<STOCK_DEALERSTOCK>();
        this.STOCK_FARMER = new HashSet<STOCK_FARMER>();
        this.Stock_OpeningBalance = new HashSet<Stock_OpeningBalance>();
        this.Stock_ReceiveDetails = new HashSet<Stock_ReceiveDetails>();
        this.Stock_SaleDetails = new HashSet<Stock_SaleDetails>();
        this.Stock_StockDetails = new HashSet<Stock_StockDetails>();
    }

    public string CropCatg_ID { get; set; }
    public string CropCatg_Name { get; set; }
    public string IsActive { get; set; }

    public virtual ICollection<Stock_Crop_Master> Stock_Crop_Master { get; set; }
    public virtual ICollection<Stock_CropVariety_Master> Stock_CropVariety_Master { get; set; }
    public virtual ICollection<Stock_DateWiseStockDetails> Stock_DateWiseStockDetails { get; set; }
    public virtual ICollection<STOCK_DEALERSALEDTL> STOCK_DEALERSALEDTL { get; set; }
    public virtual ICollection<STOCK_DEALERSTOCK> STOCK_DEALERSTOCK { get; set; }
    public virtual ICollection<STOCK_FARMER> STOCK_FARMER { get; set; }
    public virtual ICollection<Stock_OpeningBalance> Stock_OpeningBalance { get; set; }
    public virtual ICollection<Stock_ReceiveDetails> Stock_ReceiveDetails { get; set; }
    public virtual ICollection<Stock_SaleDetails> Stock_SaleDetails { get; set; }
    public virtual ICollection<Stock_StockDetails> Stock_StockDetails { get; set; }
}

public partial class Stock_CropVariety_Master
{
    public Stock_CropVariety_Master()
    {
        this.Stock_DateWiseStockDetails = new HashSet<Stock_DateWiseStockDetails>();
        this.STOCK_DEALERSALEDTL = new HashSet<STOCK_DEALERSALEDTL>();
        this.STOCK_DEALERSTOCK = new HashSet<STOCK_DEALERSTOCK>();
        this.STOCK_FARMER = new HashSet<STOCK_FARMER>();
        this.Stock_OpeningBalance = new HashSet<Stock_OpeningBalance>();
        this.Stock_Pricelist = new HashSet<Stock_Pricelist>();
        this.Stock_ReceiveDealer = new HashSet<Stock_ReceiveDealer>();
        this.Stock_ReceiveDetails = new HashSet<Stock_ReceiveDetails>();
        this.Stock_SaleDetails = new HashSet<Stock_SaleDetails>();
        this.Stock_StockDetails = new HashSet<Stock_StockDetails>();
    }

    public string CropCatg_ID { get; set; }
    public string Crop_ID { get; set; }
    public string Crop_Verid { get; set; }
    public string Crop_VerName { get; set; }
    public string IsActive { get; set; }

    public virtual Stock_Crop_Master Stock_Crop_Master { get; set; }
    public virtual Stock_CropCategory_Master Stock_CropCategory_Master { get; set; }
    public virtual ICollection<Stock_DateWiseStockDetails> Stock_DateWiseStockDetails { get; set; }
    public virtual ICollection<STOCK_DEALERSALEDTL> STOCK_DEALERSALEDTL { get; set; }
    public virtual ICollection<STOCK_DEALERSTOCK> STOCK_DEALERSTOCK { get; set; }
    public virtual ICollection<STOCK_FARMER> STOCK_FARMER { get; set; }
    public virtual ICollection<Stock_OpeningBalance> Stock_OpeningBalance { get; set; }
    public virtual ICollection<Stock_Pricelist> Stock_Pricelist { get; set; }
    public virtual ICollection<Stock_ReceiveDealer> Stock_ReceiveDealer { get; set; }
    public virtual ICollection<Stock_ReceiveDetails> Stock_ReceiveDetails { get; set; }
    public virtual ICollection<Stock_SaleDetails> Stock_SaleDetails { get; set; }
    public virtual ICollection<Stock_StockDetails> Stock_StockDetails { get; set; }
}

public partial class Stock_DateWiseStockDetails
{
    public string Dist_Code { get; set; }
    public string Godown_ID { get; set; }
    public string CropCatg_ID { get; set; }
    public string Crop_ID { get; set; }
    public string Crop_Verid { get; set; }
    public string Class { get; set; }
    public string SourceID { get; set; }
    public string Lot_No { get; set; }
    public string Bag_Size_In_kg { get; set; }
    public Nullable<int> Recv_No_Of_Bags { get; set; }
    public Nullable<decimal> Stock_Quantity { get; set; }
    public string User_Type { get; set; }
    public System.DateTime EntryDate { get; set; }

    public virtual Stock_Crop_Master Stock_Crop_Master { get; set; }
    public virtual Stock_CropCategory_Master Stock_CropCategory_Master { get; set; }
    public virtual Stock_CropVariety_Master Stock_CropVariety_Master { get; set; }
    public virtual Stock_District Stock_District { get; set; }
    public virtual Stock_Godown_Master Stock_Godown_Master { get; set; }
    public virtual Stock_Receive_Unit_Master Stock_Receive_Unit_Master { get; set; }
}

public partial class STOCK_DEALERSALE
{
    public int SALE_ID { get; set; }
    public Nullable<System.DateTime> SALE_DATE { get; set; }
    public string FARMER_ID { get; set; }
    public string TRANSACTION_ID { get; set; }
    public string CROPCATG_ID { get; set; }
    public string CROP_ID { get; set; }
    public string CROP_VERID { get; set; }
    public string CLASS { get; set; }
    public string LOT_NUMBER { get; set; }
    public string BAG_SIZE_KG { get; set; }
    public Nullable<int> NO_OF_BAGS { get; set; }
    public Nullable<decimal> ALL_IN_COST_AMOUNT { get; set; }
    public Nullable<decimal> SUBSIDY_AMOUNT { get; set; }
    public Nullable<bool> CONFIRM_STATUS { get; set; }
    public string UPDATED_BY { get; set; }
    public string UPDATED_ON { get; set; }
    public string USER_TYPE { get; set; }
    public string USERIP { get; set; }
}

public partial class STOCK_DEALERSALEDTL
{
    public string TRANSACTION_ID { get; set; }
    public string CROPCATG_ID { get; set; }
    public string CROP_ID { get; set; }
    public string CROP_VERID { get; set; }
    public string CROP_CLASS { get; set; }
    public string LOT_NUMBER { get; set; }
    public Nullable<int> BAG_SIZE_KG { get; set; }
    public Nullable<int> NO_OF_BAGS { get; set; }
    public Nullable<decimal> ALL_IN_COST_AMOUNT { get; set; }
    public Nullable<decimal> SUBSIDY_AMOUNT { get; set; }

    public virtual Stock_Crop_Master Stock_Crop_Master { get; set; }
    public virtual Stock_CropCategory_Master Stock_CropCategory_Master { get; set; }
    public virtual Stock_CropVariety_Master Stock_CropVariety_Master { get; set; }
    public virtual STOCK_DEALERSALEHDR STOCK_DEALERSALEHDR { get; set; }
}

public partial class STOCK_DEALERSALEHDR
{
    public STOCK_DEALERSALEHDR()
    {
        this.STOCK_DEALERSALEDTL = new HashSet<STOCK_DEALERSALEDTL>();
    }

    public System.DateTime SALE_DATE { get; set; }
    public string FARMER_ID { get; set; }
    public string TRANSACTION_ID { get; set; }
    public decimal TOT_SALE_AMOUNT { get; set; }
    public decimal TOT_SUB_AMOUNT { get; set; }
    public string RELEASE_STATUS { get; set; }
    public Nullable<System.DateTime> RELEASE_DATE { get; set; }
    public string REJECT_REASON { get; set; }
    public string SEASON { get; set; }
    public string FIN_YEAR { get; set; }
    public Nullable<bool> IS_ACTIVE { get; set; }
    public string UPDATED_BY { get; set; }
    public string UPDATED_ON { get; set; }
    public string USER_TYPE { get; set; }
    public string USERIP { get; set; }

    public virtual ICollection<STOCK_DEALERSALEDTL> STOCK_DEALERSALEDTL { get; set; }
}

public partial class STOCK_DEALERSTOCK
{
    public int STOCK_ID { get; set; }
    public string LICENCE_NO { get; set; }
    public string CROPCATG_ID { get; set; }
    public string CROP_ID { get; set; }
    public string CROP_VERID { get; set; }
    public string CLASS { get; set; }
    public string RECEIVE_UNITCD { get; set; }
    public string LOT_NO { get; set; }
    public string BAG_SIZE_IN_KG { get; set; }
    public Nullable<int> RECV_NO_OF_BAGS { get; set; }
    public decimal PRICE_QTL { get; set; }
    public Nullable<System.DateTime> STOCK_DATE { get; set; }
    public Nullable<decimal> STOCK_QUANTITY { get; set; }
    public Nullable<decimal> AVL_QUANTITY { get; set; }
    public string USER_TYPE { get; set; }
    public Nullable<System.DateTime> ENTRYDATE { get; set; }
    public string USERID { get; set; }
    public string USERIP { get; set; }
    public Nullable<bool> ENTRY_STATUS { get; set; }

    public virtual Stock_Crop_Master Stock_Crop_Master { get; set; }
    public virtual Stock_CropCategory_Master Stock_CropCategory_Master { get; set; }
    public virtual Stock_CropVariety_Master Stock_CropVariety_Master { get; set; }
    public virtual Stock_Receive_Unit_Master Stock_Receive_Unit_Master { get; set; }
}

public partial class Stock_District
{
    public Stock_District()
    {
        this.Stock_DateWiseStockDetails = new HashSet<Stock_DateWiseStockDetails>();
        this.Stock_Godown_Master = new HashSet<Stock_Godown_Master>();
        this.Stock_OpeningBalance = new HashSet<Stock_OpeningBalance>();
        this.Stock_ReceiveDetails = new HashSet<Stock_ReceiveDetails>();
        this.Stock_StockDetails = new HashSet<Stock_StockDetails>();
    }

    public string Dist_Code { get; set; }
    public string Dist_Name { get; set; }

    public virtual ICollection<Stock_DateWiseStockDetails> Stock_DateWiseStockDetails { get; set; }
    public virtual ICollection<Stock_Godown_Master> Stock_Godown_Master { get; set; }
    public virtual ICollection<Stock_OpeningBalance> Stock_OpeningBalance { get; set; }
    public virtual ICollection<Stock_ReceiveDetails> Stock_ReceiveDetails { get; set; }
    public virtual ICollection<Stock_StockDetails> Stock_StockDetails { get; set; }
}

public partial class STOCK_FARMER
{
    public string FARMER_ID { get; set; }
    public string TRANSACTION_ID { get; set; }
    public string CROPCATG_ID { get; set; }
    public string CROP_ID { get; set; }
    public string CROP_VERID { get; set; }
    public string CROP_CLASS { get; set; }
    public string Receive_Unitcd { get; set; }
    public string LOT_NUMBER { get; set; }
    public Nullable<int> BAG_SIZE_KG { get; set; }
    public Nullable<int> NO_OF_BAGS { get; set; }
    public Nullable<decimal> TOT_QTL { get; set; }
    public Nullable<decimal> PRICE_QTL { get; set; }
    public Nullable<decimal> ALL_IN_COST_AMOUNT { get; set; }
    public Nullable<decimal> SUBSIDY_AMOUNT { get; set; }
    public string SEASON { get; set; }
    public string FIN_YEAR { get; set; }
    public string UPDATED_BY { get; set; }
    public Nullable<System.DateTime> UPDATED_ON { get; set; }
    public string USER_TYPE { get; set; }
    public string USERIP { get; set; }
    public string TRN_TYPE { get; set; }

    public virtual Stock_Crop_Master Stock_Crop_Master { get; set; }
    public virtual Stock_CropCategory_Master Stock_CropCategory_Master { get; set; }
    public virtual Stock_CropVariety_Master Stock_CropVariety_Master { get; set; }
    public virtual Stock_Receive_Unit_Master Stock_Receive_Unit_Master { get; set; }
}

public partial class Stock_Godown_Master
{
    public Stock_Godown_Master()
    {
        this.Stock_DateWiseStockDetails = new HashSet<Stock_DateWiseStockDetails>();
        this.Stock_OpeningBalance = new HashSet<Stock_OpeningBalance>();
        this.Stock_ReceiveDealer = new HashSet<Stock_ReceiveDealer>();
        this.Stock_ReceiveDetails = new HashSet<Stock_ReceiveDetails>();
        this.Stock_SaleDetails = new HashSet<Stock_SaleDetails>();
        this.Stock_StockDetails = new HashSet<Stock_StockDetails>();
    }

    public string Dist_Code { get; set; }
    public string Godown_ID { get; set; }
    public string Godown_Name { get; set; }
    public string User_Type { get; set; }
    public string IsActive { get; set; }

    public virtual ICollection<Stock_DateWiseStockDetails> Stock_DateWiseStockDetails { get; set; }
    public virtual Stock_District Stock_District { get; set; }
    public virtual ICollection<Stock_OpeningBalance> Stock_OpeningBalance { get; set; }
    public virtual ICollection<Stock_ReceiveDealer> Stock_ReceiveDealer { get; set; }
    public virtual ICollection<Stock_ReceiveDetails> Stock_ReceiveDetails { get; set; }
    public virtual ICollection<Stock_SaleDetails> Stock_SaleDetails { get; set; }
    public virtual ICollection<Stock_StockDetails> Stock_StockDetails { get; set; }
}

public partial class Stock_OpeningBalance
{
    public int OB_ID { get; set; }
    public string Dist_Code { get; set; }
    public string Godown_ID { get; set; }
    public string CropCatg_ID { get; set; }
    public string Crop_ID { get; set; }
    public string Crop_Verid { get; set; }
    public string Class { get; set; }
    public string Receive_Unitcd { get; set; }
    public string Lot_No { get; set; }
    public string Bag_Size_In_kg { get; set; }
    public Nullable<int> Recv_No_Of_Bags { get; set; }
    public Nullable<System.DateTime> OB_date { get; set; }
    public Nullable<decimal> OB_Quantity { get; set; }
    public string User_Type { get; set; }
    public Nullable<System.DateTime> EntryDate { get; set; }
    public string UserID { get; set; }
    public string UserIP { get; set; }

    public virtual Stock_Crop_Master Stock_Crop_Master { get; set; }
    public virtual Stock_CropCategory_Master Stock_CropCategory_Master { get; set; }
    public virtual Stock_CropVariety_Master Stock_CropVariety_Master { get; set; }
    public virtual Stock_District Stock_District { get; set; }
    public virtual Stock_Godown_Master Stock_Godown_Master { get; set; }
    public virtual Stock_Receive_Unit_Master Stock_Receive_Unit_Master { get; set; }
}

public partial class Stock_Pricelist
{
    public int slno { get; set; }
    public string Crop_class { get; set; }
    public string RECEIVE_UNITCD { get; set; }
    public string Crop_Vcode { get; set; }
    public string seasons { get; set; }
    public decimal All_in_cost_Price { get; set; }
    public decimal GOI_Subsidy { get; set; }
    public decimal STATEPLAN_Subsidy { get; set; }
    public Nullable<decimal> TOT_SUBSIDY { get; set; }
    public Nullable<decimal> FARMER_PRICE { get; set; }
    public Nullable<System.DateTime> Date_of_entry { get; set; }
    public string F_Year { get; set; }

    public virtual Stock_CropVariety_Master Stock_CropVariety_Master { get; set; }
    public virtual Stock_Receive_Unit_Master Stock_Receive_Unit_Master { get; set; }
}

public partial class Stock_Receive_Unit_Master
{
    public Stock_Receive_Unit_Master()
    {
        this.Stock_DateWiseStockDetails = new HashSet<Stock_DateWiseStockDetails>();
        this.STOCK_DEALERSTOCK = new HashSet<STOCK_DEALERSTOCK>();
        this.STOCK_FARMER = new HashSet<STOCK_FARMER>();
        this.Stock_OpeningBalance = new HashSet<Stock_OpeningBalance>();
        this.Stock_Pricelist = new HashSet<Stock_Pricelist>();
        this.Stock_ReceiveDealer = new HashSet<Stock_ReceiveDealer>();
        this.Stock_ReceiveDetails = new HashSet<Stock_ReceiveDetails>();
        this.Stock_SaleDetails = new HashSet<Stock_SaleDetails>();
        this.Stock_StockDetails = new HashSet<Stock_StockDetails>();
    }

    public string AgenciesID { get; set; }
    public string Receive_Unitcd { get; set; }
    public string Receive_Unitname { get; set; }
    public string User_Type { get; set; }
    public string IsActive { get; set; }

    public virtual ICollection<Stock_DateWiseStockDetails> Stock_DateWiseStockDetails { get; set; }
    public virtual ICollection<STOCK_DEALERSTOCK> STOCK_DEALERSTOCK { get; set; }
    public virtual ICollection<STOCK_FARMER> STOCK_FARMER { get; set; }
    public virtual ICollection<Stock_OpeningBalance> Stock_OpeningBalance { get; set; }
    public virtual ICollection<Stock_Pricelist> Stock_Pricelist { get; set; }
    public virtual ICollection<Stock_ReceiveDealer> Stock_ReceiveDealer { get; set; }
    public virtual ICollection<Stock_ReceiveDetails> Stock_ReceiveDetails { get; set; }
    public virtual ICollection<Stock_SaleDetails> Stock_SaleDetails { get; set; }
    public virtual ICollection<Stock_StockDetails> Stock_StockDetails { get; set; }
}

public partial class Stock_ReceiveDealer
{
    public int RCV_NO { get; set; }
    public string LIC_NO { get; set; }
    public Nullable<System.DateTime> RECEIVE_DATE { get; set; }
    public string DD_NUMBER { get; set; }
    public string CASH_MEMO_NO { get; set; }
    public string GODOWN_ID { get; set; }
    public string RECEIVE_UNITCD { get; set; }
    public string CROP_VARIETY_CODE { get; set; }
    public string CROP_CLASS { get; set; }
    public string LOT_NO { get; set; }
    public string BAG_SIZE { get; set; }
    public string NO_OF_BAGS { get; set; }
    public Nullable<decimal> AMOUNT { get; set; }
    public string USER_TYPE { get; set; }
    public string STATUS { get; set; }
    public Nullable<System.DateTime> ENTRYDATE { get; set; }
    public string USERID { get; set; }
    public string USERIP { get; set; }

    public virtual Stock_CropVariety_Master Stock_CropVariety_Master { get; set; }
    public virtual Stock_Godown_Master Stock_Godown_Master { get; set; }
    public virtual Stock_Receive_Unit_Master Stock_Receive_Unit_Master { get; set; }
}

public partial class Stock_ReceiveDetails
{
    public int Recv_ID { get; set; }
    public string Dist_Code { get; set; }
    public string Godown_ID { get; set; }
    public string AgenciesID { get; set; }
    public string Receive_Unitcd { get; set; }
    public string Outagency_Waybillnum_Farmnm { get; set; }
    public string Challan_No { get; set; }
    public string CropCatg_ID { get; set; }
    public string Crop_ID { get; set; }
    public string Crop_Verid { get; set; }
    public string Class { get; set; }
    public string Lot_No { get; set; }
    public string Bag_Size_In_kg { get; set; }
    public Nullable<int> Recv_No_Of_Bags { get; set; }
    public Nullable<System.DateTime> Recv_Date { get; set; }
    public Nullable<decimal> Recv_Quantity { get; set; }
    public string User_Type { get; set; }
    public Nullable<System.DateTime> EntryDate { get; set; }
    public string UserID { get; set; }
    public string UserIP { get; set; }

    public virtual Stock_Crop_Master Stock_Crop_Master { get; set; }
    public virtual Stock_CropCategory_Master Stock_CropCategory_Master { get; set; }
    public virtual Stock_CropVariety_Master Stock_CropVariety_Master { get; set; }
    public virtual Stock_District Stock_District { get; set; }
    public virtual Stock_Godown_Master Stock_Godown_Master { get; set; }
    public virtual Stock_Receive_Unit_Master Stock_Receive_Unit_Master { get; set; }
}

public partial class Stock_SaleDetails
{
    public int SALE_ID { get; set; }
    public string SUPPLY_TYPE { get; set; }
    public string CREDIT_BILL_NO { get; set; }
    public Nullable<System.DateTime> mDATE { get; set; }
    public string DEPT_TYPE { get; set; }
    public string GODOWN_ID { get; set; }
    public Nullable<System.DateTime> SALE_DATE { get; set; }
    public string SALE_TO { get; set; }
    public string DD_NUMBER { get; set; }
    public string CASH_MEMO_NO { get; set; }
    public Nullable<decimal> AMOUNT { get; set; }
    public string CROPCATG_ID { get; set; }
    public string CROP_ID { get; set; }
    public string CROP_VERID { get; set; }
    public string CLASS { get; set; }
    public string Receive_Unitcd { get; set; }
    public string LOT_NUMBER { get; set; }
    public string BAG_SIZE_KG { get; set; }
    public Nullable<int> SALE_NO_OF_BAG { get; set; }
    public Nullable<bool> CONFIRM_STATUS { get; set; }
    public string STATUS { get; set; }
    public string UPDATED_BY { get; set; }
    public Nullable<System.DateTime> UPDATED_ON { get; set; }
    public string USER_TYPE { get; set; }
    public string USERIP { get; set; }
    public string IS_ACTIVE { get; set; }

    public virtual Stock_Crop_Master Stock_Crop_Master { get; set; }
    public virtual Stock_CropCategory_Master Stock_CropCategory_Master { get; set; }
    public virtual Stock_CropVariety_Master Stock_CropVariety_Master { get; set; }
    public virtual Stock_Godown_Master Stock_Godown_Master { get; set; }
    public virtual Stock_Receive_Unit_Master Stock_Receive_Unit_Master { get; set; }
}

public partial class Stock_StockDetails
{
    public int Stock_ID { get; set; }
    public string Dist_Code { get; set; }
    public string Godown_ID { get; set; }
    public string CropCatg_ID { get; set; }
    public string Crop_ID { get; set; }
    public string Crop_Verid { get; set; }
    public string Class { get; set; }
    public string Receive_Unitcd { get; set; }
    public string Lot_No { get; set; }
    public string Bag_Size_In_kg { get; set; }
    public Nullable<int> Recv_No_Of_Bags { get; set; }
    public Nullable<System.DateTime> Stock_Date { get; set; }
    public Nullable<decimal> Stock_Quantity { get; set; }
    public Nullable<decimal> Avl_Quantity { get; set; }
    public string User_Type { get; set; }
    public Nullable<System.DateTime> EntryDate { get; set; }
    public string UserID { get; set; }
    public string UserIP { get; set; }
    public string Entry_Status { get; set; }

    public virtual Stock_Crop_Master Stock_Crop_Master { get; set; }
    public virtual Stock_CropCategory_Master Stock_CropCategory_Master { get; set; }
    public virtual Stock_CropVariety_Master Stock_CropVariety_Master { get; set; }
    public virtual Stock_District Stock_District { get; set; }
    public virtual Stock_Godown_Master Stock_Godown_Master { get; set; }
    public virtual Stock_Receive_Unit_Master Stock_Receive_Unit_Master { get; set; }
}

public partial class Stock_SupplyType
{
    public int SUPPLY_ID { get; set; }
    public string SUPPLY_NAME { get; set; }
    public string USER_TYPE { get; set; }
    public string ISACTIVE { get; set; }
}

public partial class Stock_UserActivity_Log
{
    public string UserID { get; set; }
    public System.DateTime ActivityDate { get; set; }
    public string ActivityType { get; set; }
    public string UserIP { get; set; }
    public string Activity { get; set; }
    public string Remark { get; set; }
    public string PageURL { get; set; }
    public string OS { get; set; }
    public string BWSER { get; set; }
}

public partial class Stock_UserProfile
{
    public string UserId { get; set; }
    public Nullable<int> UID { get; set; }
    public string Dist_Code { get; set; }
    public string Name { get; set; }
    public string FullName { get; set; }
    public string Mobile { get; set; }
    public string Contact { get; set; }
    public string email { get; set; }
    public string User_Type { get; set; }
    public string delFlag { get; set; }
    public string logStatus { get; set; }
}

public partial class Stock_Users
{
    public Stock_Users()
    {
        this.LoginAccesses = new HashSet<LoginAccess>();
    }

    public string UserID { get; set; }
    public string Passwd { get; set; }
    public string Passwd2 { get; set; }
    public string Passwd3 { get; set; }
    public string User_Type { get; set; }
    public Nullable<System.DateTime> Date_Create { get; set; }
    public Nullable<System.DateTime> Last_Pwd_Change { get; set; }
    public Nullable<int> Login_Attempt_Fail { get; set; }
    public Nullable<System.DateTime> Login_Attempt_Last { get; set; }
    public Nullable<System.DateTime> Login_Success_Last { get; set; }
    public string Login_Status { get; set; }
    public string SessionID { get; set; }

    public virtual ICollection<LoginAccess> LoginAccesses { get; set; }
}

public partial class tmp_FarmerSale
{
    public int SALE_ID { get; set; }
    public string RANDOM_NO { get; set; }
    public string CROPCATG_ID { get; set; }
    public string CROP_ID { get; set; }
    public string CROP_VERID { get; set; }
    public string CROP_CLASS { get; set; }
    public string LOT_NO { get; set; }
    public string Receive_Unitcd { get; set; }
    public Nullable<int> BAG_SIZE_KG { get; set; }
    public Nullable<int> NO_OF_BAGS { get; set; }
    public Nullable<decimal> QUANTITY { get; set; }
    public Nullable<decimal> PRICE_QTL { get; set; }
    public Nullable<decimal> AMOUNT { get; set; }
    public Nullable<bool> IS_ACTIVE { get; set; }
}

public partial class tmp_SaleDtls
{
    public int TMP_SALEID { get; set; }
    public string Receive_Unitcd { get; set; }
    public string RANDOM_NO { get; set; }
    public string CATEGORY_ID { get; set; }
    public string CROP_ID { get; set; }
    public string VARIETY_ID { get; set; }
    public string CROP_CLASS { get; set; }
    public string LOT_NO { get; set; }
    public Nullable<int> BAG_SIZE { get; set; }
    public Nullable<int> NO_OF_BAGS { get; set; }
    public Nullable<decimal> QUANTITY_QTL { get; set; }
}
