//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class StockEntities : DbContext
{
    public StockEntities()
        : base("name=StockEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<LoginAccess> LoginAccesses { get; set; }
    public DbSet<Stock_Agencies_Master> Stock_Agencies_Master { get; set; }
    public DbSet<Stock_Crop_Master> Stock_Crop_Master { get; set; }
    public DbSet<Stock_CropCategory_Master> Stock_CropCategory_Master { get; set; }
    public DbSet<Stock_CropVariety_Master> Stock_CropVariety_Master { get; set; }
    public DbSet<Stock_DateWiseStockDetails> Stock_DateWiseStockDetails { get; set; }
    public DbSet<STOCK_DEALERSALE> STOCK_DEALERSALE { get; set; }
    public DbSet<STOCK_DEALERSALEDTL> STOCK_DEALERSALEDTL { get; set; }
    public DbSet<STOCK_DEALERSALEHDR> STOCK_DEALERSALEHDR { get; set; }
    public DbSet<STOCK_DEALERSTOCK> STOCK_DEALERSTOCK { get; set; }
    public DbSet<Stock_District> Stock_District { get; set; }
    public DbSet<STOCK_FARMER> STOCK_FARMER { get; set; }
    public DbSet<Stock_Godown_Master> Stock_Godown_Master { get; set; }
    public DbSet<Stock_OpeningBalance> Stock_OpeningBalance { get; set; }
    public DbSet<Stock_Pricelist> Stock_Pricelist { get; set; }
    public DbSet<Stock_Receive_Unit_Master> Stock_Receive_Unit_Master { get; set; }
    public DbSet<Stock_ReceiveDealer> Stock_ReceiveDealer { get; set; }
    public DbSet<Stock_ReceiveDetails> Stock_ReceiveDetails { get; set; }
    public DbSet<Stock_SaleDetails> Stock_SaleDetails { get; set; }
    public DbSet<Stock_StockDetails> Stock_StockDetails { get; set; }
    public DbSet<Stock_SupplyType> Stock_SupplyType { get; set; }
    public DbSet<Stock_UserActivity_Log> Stock_UserActivity_Log { get; set; }
    public DbSet<Stock_UserProfile> Stock_UserProfile { get; set; }
    public DbSet<Stock_Users> Stock_Users { get; set; }
    public DbSet<tmp_FarmerSale> tmp_FarmerSale { get; set; }
    public DbSet<tmp_SaleDtls> tmp_SaleDtls { get; set; }
}
